// Generated by packages/shared/scripts/generate-opening-book.mjs; do not edit.
//
// The 3864 named openings of lichess-org/chess-openings
// (https://github.com/lichess-org/chess-openings), commit 5a13018164f6bd88f48b3dc31a8e2a39f31a060a,
// files a.tsv, b.tsv, c.tsv, d.tsv, e.tsv. That data is dedicated to the public domain under CC0 1.0
// (https://creativecommons.org/publicdomain/zero/1.0/).
//
// Zstd of the move tree, one row per move, depth-first: "<depth>\t<uci>[\t<eco>\t<name>]".
// openingBookText() inflates the sibling .txt.zst for parseOpeningBook.

import { readFileSync } from "node:fs";
import { zstdDecompressSync } from "node:zlib";
import { fileURLToPath } from "node:url";

const compressed = readFileSync(fileURLToPath(new URL("./opening-book.txt.zst", import.meta.url)));

let text: string | null = null;

/** The book's move tree, inflated once. */
export function openingBookText(): string {
  text ??= zstdDecompressSync(compressed).toString("utf8");
  return text;
}
